package com.ramonvicente.employeeservice.service;

import com.ramonvicente.employeeservice.dto.auth.LoginRequest;
import com.ramonvicente.employeeservice.dto.auth.RegistrationRequest;
import com.ramonvicente.employeeservice.dto.auth.RegistrationResult;
import com.ramonvicente.employeeservice.dto.auth.TokenResponse;
import com.ramonvicente.employeeservice.model.User;

public interface UserService {

    /**
     * Creates a new {@link User} in the database from the provided {@link RegistrationRequest}.
     * @param registrationRequest DTO containing user data to be registered.
     * @return {@link RegistrationResult} DTO containing the registered {@link User} data.
     */
    RegistrationResult registerUser(RegistrationRequest registrationRequest);

    /**
     * Get the user {@link TokenResponse} generated by JWT.
     * @param loginRequest DTO containing user data from existing {@link User}.
     * @return {@link TokenResponse} DTO containing the authentication token for {@link User}.
     */
    TokenResponse login(LoginRequest loginRequest);
}
